name: Metrics

on:
  schedule:
    - cron: "0 0 * * *" # tous les jours à minuit UTC
  workflow_dispatch:    # exécution manuelle
  push:
    branches: ["master", "main"] # optionnel

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: VinceBmmrt/metricsGithub@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
