name: GitHub Metrics

on:
  push:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate In-Depth Language Metrics
        uses: VinceBmmrt/metricsGithub@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 20
          plugin_languages_analysis_timeout: 15
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot

