name: GitHub Metrics

on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Metrics
        uses: VinceBmmrt/metricsGithub@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.user.svg
          template: classic
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
