name: GitHub Metrics

on:
  schedule:
    - cron: "59 23 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate In-Depth Language Metrics
        uses: VinceBmmrt/metricsGithub@master 
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.plugin.languages.indepth.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 100
          plugin_languages_threshold: 0%
          plugin_languages_categories: programming, markup, data, prose
          commits_authoring: |
            VinceBmmrt
            vincetbommert75@gmail.com

