name: Metrics

on:
  schedule:
    - cron: '0 0 * * *'  # tous les jours à minuit UTC
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Generate GitHub Metrics
        uses: VinceBmmrt/metricsGithub@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          template: classic
          output: github-metrics.svg
          dark: true
          theme: Tokyonight
          width: regular
          languages: true
          noCache: true
          indepth: true
          showContribCount: true
          showReposContributedToCount: true
          showTotalContributions: true
          stats: commits,prs,issues,reviews,followers,stars,gists
          includeRepos: '*'
          excludeRepos: ''
          showAvailableForHire: true
          showSponsors: true
          showOrgs: true

      - name: Commit and push metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore(metrics): mise à jour complète des stats GitHub'
          file_pattern: github-metrics.svg
          branch: master
          push_options: '--force'
