name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"  # tous les jours à minuit UTC
  workflow_dispatch:
  push:
    branches: ["master", "main"]

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: VinceBmmrt/metricsGithub@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config: |
            theme: dark
            base: true
            core: true
            plugins:
              - achievements
              - activity
              - calendar
              - code
              - contributors
              - discussions
              - followup
              - gists
              - habits
              - isocalendar
              - languages
              - licenses
              - lines
              - notable
              - people
              - projects
              - reactions
              - repositories
              - skyline
              - sponsors
              - sponsorships
              - stargazers
              - starlists
              - stars
              - traffic
            stats:
              commits: true
              prs: true
              issues: true
              reviews: true
              followers: true
              stars: true
              gists: true
