name: Metrics
on:
  schedule:
    - cron: '0 0 * * *'  # Exécution quotidienne à minuit UTC
  workflow_dispatch:     # Permet l'exécution manuelle

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v2.9.3
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: VinceBmmrt
          template: classic
          base: header, repositories
          plugin_languages: true
          plugin_languages_limit: 20
