name: Metrics
on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@v2.9.3
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: VinceBmmrt
          template: classic
          plugin_languages: true
          plugin_languages_limit: 20
